import { Header } from '@/comonents/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { css } from '../../styled-system/css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Header />
      <body className={bodyStyle}>
        <div className={containerStyle}>
          {children}
        </div>
      </body>
    </html>
  )
}

// sm: '640px',
// md: '768px',
// lg: '1024px',
// xl: '1280px',
// '2xl': '1536px'
const bodyStyle = css({
  width: '100%',
  height: '100vh',
  margin: '120px 0',
  background: 'gray.200',
});

const containerStyle = css({
  minHeight: 'calc(100vh - 120px)',
  padding: '16px',
  maxWidth: 'calc(100vw - 16px)',
  background: 'white',
  margin: '0 auto',
  sm: {
    width: 'calc(608px)',
  },
  md: {
    width: '750px',
  },
});

